export const colorTokens = [
  "background",
  "foreground",
  "card",
  "card-foreground",
  "popover",
  "popover-foreground",
  "primary",
  "primary-foreground",
  "secondary",
  "secondary-foreground",
  "muted",
  "muted-foreground",
  "accent",
  "accent-foreground",
  "destructive",
  "border",
  "input",
  "ring",
  "brand",
  "brand-foreground",
  "brand-soft",
  "brand-soft-foreground",
  "control-indicator",
  "chart-1",
  "chart-2",
  "chart-3",
  "chart-4",
  "chart-5",
  "sidebar",
  "sidebar-foreground",
  "sidebar-primary",
  "sidebar-primary-foreground",
  "sidebar-accent",
  "sidebar-accent-foreground",
  "sidebar-border",
  "sidebar-ring",
  "success",
  "success-soft",
  "warning",
  "warning-soft",
  "in-progress",
  "in-progress-soft",
] as const

export type ColorToken = (typeof colorTokens)[number]

export type ColorMode = "light" | "dark"

export type ThemeColors = Record<ColorMode, Partial<Record<ColorToken, string>>>
